name: Test

on: 
  workflow_dispatch:
    inputs:
      caller:
        description: Caller URL
        required: false
        default: '...'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.caller }}
        run: echo "Hello World"